# data.R -- roxygen documentation for the bundled known-truth dataset
# `ssi_examples`. The dataset itself is generated by (and fully reproducible
# from) data-raw/make_ssi_examples.R. Do not edit the .rda by hand; rerun that
# script. Every column and every data-generating process is documented here so
# a stranger can reproduce the data from the equations alone.

#' Known-truth seasonal-adjustment examples (one per identification world)
#'
#' @description
#' A small, bundled collection of simulated quarterly series, each paired with
#' its **true nonseasonal counterfactual** -- the series one would observe if
#' the seasonality were absent. Because the counterfactual is known by
#' construction, `ssi_examples` lets vignettes, examples, and tests measure a
#' seasonal adjustment's accuracy *against truth*, a demonstration no real
#' dataset permits.
#'
#' There is exactly one series per identification "world". The world is the
#' modelling commitment that the phase rule encodes (filter-versus-components
#' identification is not testable at second order; see [seas_ssi()] and
#' `vignette("two-worlds")`), so each world exercises a different correct
#' adjustment:
#' \describe{
#'   \item{`"filter"`}{Shared-innovation (deconvolution) world: the seasonal
#'     series and its counterfactual are driven by the *same* innovations. The
#'     minimum-phase rule (`phase_rule = "minimum"`) is correct here.}
#'   \item{`"components"`}{Independent-seasonal world: an added seasonal
#'     component with its own innovations sits on top of the nonseasonal part.
#'     The zero-phase / Wiener-shrinkage rule (`phase_rule = "zero"`) is correct
#'     here.}
#'   \item{`"line"`}{Deterministic seasonality: a fixed, frozen quarterly
#'     pattern (a line spectrum) rather than a stochastic band.}
#' }
#'
#' @format A [tibble::tibble()] with 3 rows (one per world) and 4 columns:
#' \describe{
#'   \item{world}{Character, the identification world:
#'     `"filter"`, `"components"`, or `"line"`.}
#'   \item{x}{A list column of [stats::ts()] objects (quarterly, `frequency = 4`,
#'     length `120`, starting `2000 Q1`): the observed **seasonal** series.}
#'   \item{truth}{A list column of [stats::ts()] objects, aligned one-to-one
#'     with `x`: the **true nonseasonal counterfactual** for each `x`.}
#'   \item{params}{A list column of named lists recording that world's
#'     data-generating parameters (`phi`, `Phi`, amplitudes, innovation
#'     standard deviations, `spin`, `n`, `frequency`, `seed`), the generating
#'     `equation`, and the defining `identity` used as a cross-check. It also
#'     stores the world's true seasonal component (`x - truth`) directly: the
#'     `"components"` world under `seasonal` and the `"line"` world under
#'     `pattern` (the `"filter"` world's seasonal part is instead pinned by
#'     its deconvolution `identity`).}
#' }
#'
#' @details
#' All three series are quarterly (`s = 4`), length `n = 120` (30 years,
#' `2000 Q1 .. 2029 Q4`), generated after a spin-up of `400` discarded quarters
#' from zero initial conditions, from a single master seed (`20260722`) consumed
#' in world order (filter, then components, then line). The session's
#' calibration is used throughout: nonseasonal AR(1) coefficient `phi = 0.5`,
#' seasonal coefficient `Phi = 0.9`, and (deterministic-line only) amplitudes
#' `A12 = 1.5` and `A3 = 2.0`. Every innovation stream is standard normal
#' (`sd = 1`). Writing `B` for the backshift operator (`B x_t = x_{t-1}`):
#'
#' \strong{filter world.} The observed series and its counterfactual `xNS`
#' share one innovation stream `eps`:
#' \deqn{(1 - \phi B)(1 - \Phi B^{s})\, x_t = \varepsilon_t, \qquad
#'       (1 - \phi B)\, x^{NS}_t = \varepsilon_t.}
#' Equivalently `x_t = phi x_{t-1} + Phi x_{t-4} - phi Phi x_{t-5} + eps_t` and
#' `xNS_t = phi xNS_{t-1} + eps_t`. Applying `(1 - phi B)` to both definitions
#' cancels the nonseasonal factor and yields the exact deconvolution identity
#' \deqn{x^{NS}_t = x_t - \Phi\, x_{t-4},}
#' which holds on the retained window to machine precision and is the generation
#' cross-check. `truth` is `xNS`.
#'
#' \strong{components world.} A nonseasonal AR(1) part `a` (the truth) and an
#' independent seasonal AR part `s`, with their own innovation streams `u` and
#' `eta`, are added:
#' \deqn{(1 - \phi B)\, a_t = u_t, \qquad (1 - \Phi B^{s})\, s_t = \eta_t,
#'       \qquad x_t = a_t + s_t.}
#' `truth` is `a`; by construction `x_t - truth_t = s_t` exactly, and
#' `(1 - Phi B^s)` applied to `x - truth` recovers `eta`.
#'
#' \strong{line world.} A nonseasonal AR(1) part `a` (the truth) plus a fixed,
#' deterministic quarterly pattern:
#' \deqn{(1 - \phi B)\, a_t = u_t, \qquad
#'       p_t = A_{12}\cos(\pi t/2) + A_{12}\sin(\pi t/2) + A_{3}\cos(\pi t),
#'       \qquad x_t = a_t + p_t.}
#' The pattern has power only at the annual harmonic (`pi/2`, amplitude `A12`)
#' and the semiannual / Nyquist harmonic (`pi`, amplitude `A3`) -- a line
#' spectrum. `truth` is `a`; by construction `x_t - truth_t = p_t` exactly, and
#' the pattern is stored in `params$pattern`.
#'
#' @source Generated by `data-raw/make_ssi_examples.R` in the package sources
#'   (seeded and rerunnable; the script prints the per-world identity
#'   cross-checks, all `~1e-15`).
#'
#' @seealso [seas_adjust()], [seas_ssi()], [benchmark_totals()]
#'
#' @examples
#' # The filter-world series and its true nonseasonal counterfactual:
#' fw    <- ssi_examples[ssi_examples$world == "filter", ]
#' x     <- fw$x[[1]]
#' truth <- fw$truth[[1]]
#'
#' # The defining deconvolution identity holds to machine precision:
#' Phi <- fw$params[[1]]$Phi
#' max(abs(truth[5:120] - (x[5:120] - Phi * x[1:116])))  # ~1e-15
#'
#' # Adjust, then compare against the known truth (demeaned; the shared-
#' # innovation gain at frequency zero is not removable -- see the vignettes):
#' adj <- seas_adjust(x, phase_rule = "minimum")
#' dm  <- function(z) z - mean(z)
#' c(none = sqrt(mean((dm(x)             - dm(truth))^2)),
#'   adj  = sqrt(mean((dm(adjusted(adj)) - dm(truth))^2)))
"ssi_examples"
