# Frequency-grid and bin machinery for the freqseas seasonality workflow.
#
# This file provides the geometry the whole pipeline stands on: the
# positive-frequency Fourier grid, the seasonal frequency set, the equal-width
# bin partition that classifies bins as seasonal / nonseasonal, the mapping of
# that classification onto Fourier-ordinate index sets (including the exact
# harmonic ordinates that power the line/band specification test), and the
# bin-count suggester `suggest_M()` (the only export here).

#' Positive-frequency Fourier grid
#'
#' Index structure of the positive-frequency Fourier ordinates for a series of
#' length `n`. No data enter; this is pure grid geometry. Unlike the earlier
#' reference implementation, the grid **includes the Nyquist ordinate** for even
#' `n` (i.e. `omega_pos` lives on `(0, pi]`), because the adjustment machinery
#' targets the Nyquist frequency.
#'
#' @param n Single integer, the series length (`>= 8`).
#'
#' @return A named list with components:
#'   \describe{
#'     \item{`n`}{The integer length.}
#'     \item{`n_spec`}{Number of positive-side spectral ordinates,
#'       `floor(n / 2)` (includes Nyquist when `n` is even).}
#'     \item{`j_grid`}{Integer vector `1:n_spec`, the harmonic indices.}
#'     \item{`pos_idx`}{Integer vector `j_grid + 1L`, the positions of these
#'       ordinates in the full R DFT vector (which is 1-indexed with DC at
#'       position 1).}
#'     \item{`omega_pos`}{Numeric vector `2 * pi * j_grid / n` in `(0, pi]`.}
#'     \item{`idx_nyq`}{Position of the Nyquist ordinate **in the full DFT
#'       vector** (`n / 2 + 1L`) when `n` is even, `NA_integer_` when `n` is
#'       odd. Reported in full-DFT coordinates to match `pos_idx` and the
#'       surgery machinery's Hermitian-symmetry guards.}
#'   }
#'
#' @keywords internal
#' @noRd
fourier_grid <- function(n) {
  if (length(n) != 1L || !is.finite(n) || n < 8L) {
    stop("`n` must be a single integer >= 8.")
  }
  n      <- as.integer(n)
  n_spec <- n %/% 2L            # floor(n/2): includes Nyquist for even n
  j_grid <- seq_len(n_spec)

  idx_nyq <- if (n %% 2L == 0L) n %/% 2L + 1L else NA_integer_

  list(
    n         = n,
    n_spec    = n_spec,
    j_grid    = j_grid,
    pos_idx   = j_grid + 1L,
    omega_pos = 2 * pi * j_grid / n,
    idx_nyq   = idx_nyq
  )
}

#' Seasonal frequencies Omega_G(P, N)
#'
#' The seasonal angular frequencies on `(0, pi]` generated by fundamental-period
#' multipliers `P` at data frequency `N` (observations per year), optionally
#' dropping the Nyquist frequency `pi`.
#'
#' The default **includes** Nyquist (`exclude_nyquist = FALSE`): the adjustment
#' targets the Nyquist harmonic when it is seasonal. Callers that must reproduce
#' the Nyquist-excluding convention (the EVT detection test and `suggest_M()`)
#' pass `exclude_nyquist = TRUE` explicitly.
#'
#' @param P Nonempty vector of positive integers (fundamental-period
#'   multipliers).
#' @param N Single positive integer, observations per year (e.g. 12 monthly,
#'   4 quarterly).
#' @param exclude_nyquist Logical; drop `omega = pi` if present. Default
#'   `FALSE`.
#'
#' @return Sorted numeric vector of unique angular frequencies in `(0, pi]`
#'   (or `(0, pi)` when `exclude_nyquist = TRUE`).
#'
#' @keywords internal
#' @noRd
omega_seasonal <- function(P, N, exclude_nyquist = FALSE) {
  if (length(P) < 1L || any(!is.finite(P)) || any(P < 1L)) {
    stop("`P` must be a nonempty vector of positive integers.")
  }
  if (length(N) != 1L || !is.finite(N) || N <= 0) {
    stop("`N` must be a single positive integer.")
  }
  P <- unique(as.integer(P))
  N <- as.integer(N)

  out <- numeric(0)
  for (p in P) {
    denom <- p * N
    kmax  <- denom %/% 2L
    if (kmax >= 1L) {
      out <- c(out, 2 * pi * seq_len(kmax) / denom)
    }
  }
  out <- sort(unique(out))
  out <- out[out > 0 & out <= pi]

  if (isTRUE(exclude_nyquist)) {
    tol <- .Machine$double.eps^0.5
    out <- out[abs(out - pi) > tol]
  }
  out
}

#' Equal-width bin partition of (0, pi]
#'
#' Partition `(0, pi]` into `M` equal-width bins and classify each bin as
#' seasonal or nonseasonal according to whether it contains an element of
#' `omega_seasonal(P, N)`.
#'
#' A boundary-collision warning fires when an **interior** seasonal frequency
#' lands (within `boundary_tol`) on an interior bin break, since then its bin
#' assignment is numerically ambiguous. The domain endpoints `0` and `pi` are
#' excluded from this check: `pi` is always the right endpoint `breaks[M + 1]`
#' and `cut(right = TRUE)` assigns it unambiguously to bin `M`, so a seasonal
#' Nyquist frequency is not a collision (this matters because the default
#' `exclude_nyquist = FALSE` puts `pi` into `omega_G`).
#'
#' @param M Integer `>= 2`, number of bins.
#' @param P,N Seasonal-period multiplier(s) and data frequency, passed to
#'   `omega_seasonal()`. Echoed back in the return value so downstream code
#'   (e.g. [index_sets()]) can recover the exact harmonic set.
#' @param omega_pos Numeric vector of positive-frequency ordinates (from
#'   [fourier_grid()]).
#' @param band `"full"` (default) uses all `M` bins; `"between_seasonal_extremes"`
#'   restricts attention to the bins spanning the seasonal extremes.
#' @param exclude_nyquist Logical, passed to `omega_seasonal()`. Default
#'   `FALSE`.
#' @param boundary_tol Numerical tolerance for the interior boundary-collision
#'   warning. Default `1e-12`.
#'
#' @return A named list: `M`, `breaks`, `band`, `P`, `N` (echoed), `bin_pos`
#'   (integer bin index for each `omega_pos`), `omega_G` (the seasonal
#'   frequencies used), `M1`/`M0` (seasonal / nonseasonal bin index sets), and
#'   `M_star`/`M1_eff`/`M0_eff` (the effective sets after band restriction).
#'
#' @keywords internal
#' @noRd
mbin_partition <- function(M, P, N, omega_pos,
                           band            = c("full", "between_seasonal_extremes"),
                           exclude_nyquist = FALSE,
                           boundary_tol    = 1e-12) {
  band <- match.arg(band)
  if (length(M) != 1L || !is.finite(M) || M < 2L) stop("`M` must be an integer >= 2.")
  M <- as.integer(M)

  breaks  <- seq(0, pi, length.out = M + 1L)
  bin_pos <- cut(omega_pos, breaks = breaks, right = TRUE,
                 include.lowest = FALSE, labels = FALSE)

  omega_G <- omega_seasonal(P = P, N = N, exclude_nyquist = exclude_nyquist)
  if (length(omega_G) == 0L) stop("Omega_G is empty given P and N.")

  # Warn only if a seasonal frequency numerically hits an INTERIOR break;
  # the endpoints 0 and pi are unambiguous and excluded from the check.
  interior_breaks <- breaks[-c(1L, length(breaks))]
  if (length(interior_breaks) > 0L) {
    dist_to_boundary <- vapply(
      omega_G,
      function(w) min(abs(w - interior_breaks)),
      numeric(1)
    )
    if (any(dist_to_boundary < boundary_tol)) {
      warning("One or more seasonal frequencies sit on an interior bin boundary; ",
              "consider changing M so they fall in bin interiors.")
    }
  }

  bin_seas <- cut(omega_G, breaks = breaks, right = TRUE,
                  include.lowest = FALSE, labels = FALSE)
  M1 <- sort(unique(bin_seas[!is.na(bin_seas)]))
  M0 <- setdiff(seq_len(M), M1)
  if (length(M1) == 0L) stop("M1 is empty.")
  if (length(M0) == 0L) stop("M0 is empty.")

  if (band == "between_seasonal_extremes") {
    M_star <- seq(min(M1), max(M1))
    M1_eff <- intersect(M1, M_star)
    M0_eff <- setdiff(M_star, M1_eff)
  } else {
    M_star <- seq_len(M)
    M1_eff <- M1
    M0_eff <- M0
  }

  list(
    M       = M,
    breaks  = breaks,
    band    = band,
    P       = unique(as.integer(P)),
    N       = as.integer(N),
    bin_pos = bin_pos,
    omega_G = omega_G,
    M1      = M1,
    M0      = M0,
    M_star  = M_star,
    M1_eff  = M1_eff,
    M0_eff  = M0_eff
  )
}

#' Fourier-ordinate index sets from a bin partition
#'
#' Map the `M`-bin seasonal / nonseasonal classification onto Fourier-ordinate
#' index sets, in both positive-side coordinates and full-DFT coordinates, and
#' isolate the exact-harmonic ordinates that drive the line/band specification
#' test.
#'
#' @param part A partition list from [mbin_partition()] (must carry `bin_pos`,
#'   `M1_eff`, `M0_eff`, `P`, `N`).
#' @param grid A grid list from [fourier_grid()] (must carry `omega_pos`,
#'   `pos_idx`, `n`). `part$bin_pos` and `grid$omega_pos` must align
#'   element-for-element (both length `n_spec`).
#'
#' @return A named list:
#'   \describe{
#'     \item{`J1`, `J0`}{Positive-side indices (into `1:n_spec`, i.e. into
#'       `grid$omega_pos`) of the seasonal / nonseasonal ordinates.}
#'     \item{`J1_full`}{Full-DFT positions of the seasonal ordinates **including
#'       their conjugate (negative-frequency) mirrors** — the coordinate the
#'       Hermitian-symmetric surgery operates in. The Nyquist ordinate is
#'       self-conjugate and appears once.}
#'     \item{`J0_full`}{Full-DFT positions of the nonseasonal ordinates,
#'       **positive side only** (no mirrors): donor sampling draws from these and
#'       would double-count if the conjugates were included.}
#'     \item{`N1`, `N0`}{Cardinalities `length(J1)`, `length(J0)`.}
#'     \item{`H`}{Positive-side indices of the exact-harmonic ordinates: those
#'       `j` whose `omega_j` matches an element of
#'       `omega_seasonal(P, N, exclude_nyquist = FALSE)` within `1e-9`. These are
#'       the spectral lines; the seasonal Nyquist harmonic is included when
#'       present.}
#'     \item{`S`}{`setdiff(J1, H)`, the shoulder ordinates (seasonal band minus
#'       the exact harmonics).}
#'   }
#'
#' @keywords internal
#' @noRd
index_sets <- function(part, grid) {
  bin_pos <- part$bin_pos
  pos_idx <- grid$pos_idx
  if (length(bin_pos) != length(pos_idx)) {
    stop("`part$bin_pos` and `grid$pos_idx` must have the same length.")
  }

  J1 <- which(bin_pos %in% part$M1_eff)
  J0 <- which(bin_pos %in% part$M0_eff)
  if (length(J1) == 0L) stop("No seasonal Fourier ordinates (J1 empty).")
  if (length(J0) == 0L) stop("No nonseasonal Fourier ordinates (J0 empty).")

  # Exact harmonic ordinates: match omega_pos to the full seasonal set
  # (Nyquist included) within tolerance.
  omega_H <- omega_seasonal(P = part$P, N = part$N, exclude_nyquist = FALSE)
  H <- which(vapply(
    grid$omega_pos,
    function(w) any(abs(w - omega_H) < 1e-9),
    logical(1)
  ))
  S <- setdiff(J1, H)

  # Full-DFT seasonal positions plus conjugate mirrors (position k <-> n-k+2);
  # the Nyquist position maps to itself and unique() collapses it.
  n         <- grid$n
  j1_dft    <- pos_idx[J1]
  j1_mirror <- n - j1_dft + 2L
  J1_full   <- sort(unique(c(j1_dft, j1_mirror)))

  # Nonseasonal donors: positive side only (no mirrors).
  J0_full <- pos_idx[J0]

  list(
    J1      = J1,
    J0      = J0,
    J1_full = J1_full,
    J0_full = J0_full,
    N1      = length(J1),
    N0      = length(J0),
    H       = H,
    S       = S
  )
}

#' Suggest a bin count M for the seasonal/nonseasonal partition
#'
#' Choose a fixed number of frequency bins `M` for an equal-width partition of
#' `(0, pi)` so that every distinct seasonal frequency in `omega_seasonal(P, N)`
#' occupies its own bin (one harmonic per bin), no seasonal frequency lands on a
#' bin boundary, and the seasonal-bin share `K_M / M` sits close to `target_rho`
#' (within `rho_bounds` when possible).
#'
#' The package's binning is **offset-free**: bins are the fixed partition
#' `((m - 1) pi / M, m pi / M]`. Accordingly the default `offset_grid = 0` only
#' considers that partition. The reference implementation shipped
#' `offset_grid = c(0, 0.5)`, which can select a boundary-avoiding partition
#' shifted by half a bin; such offsets are **not realizable** by the package's
#' binning (they would require an `alpha`-shifted `mbin_partition`), so they are
#' documented but off by default. A nonzero offset can therefore return an `M`
#' with a nonzero `offset_u`/`alpha` that the rest of the pipeline cannot honor.
#'
#' @param P Nonempty vector of positive integers (fundamental-period
#'   multipliers).
#' @param N Single positive integer, observations per year.
#' @param n_obs Optional series length; when supplied, enables the average
#'   ordinates-per-bin diagnostic and the optional occupancy constraint.
#' @param target_rho Target seasonal-bin share `K_M / M`. Default `0.25`.
#' @param rho_bounds Length-2 increasing acceptable range for `K_M / M`.
#'   Default `c(0.15, 0.35)`.
#' @param min_ordinates_per_bin Optional minimum average Fourier ordinates per
#'   bin (requires `n_obs`).
#' @param exclude_nyquist Passed to `omega_seasonal()`. Default `TRUE` (the
#'   detection convention).
#' @param search_min,search_max Optional integer bounds for the `M` search;
#'   sensible defaults are derived from `H` and `target_rho`.
#' @param offset_grid Grid of partition offsets `alpha / (pi / M)` in `[0, 1)`
#'   tried per `M`; the first boundary-safe offset is kept. Default `0`
#'   (offset-free; see Details).
#' @param boundary_tol Numerical tolerance for detecting boundary hits. Default
#'   `.Machine$double.eps^0.5`.
#' @param return_candidates If `TRUE`, attach the full candidate table.
#'
#' @return A list with the suggested `M`, the number of seasonal frequencies
#'   `H`, the number of seasonal bins `K_M`, the realized share `rho_M`, the
#'   partition offset `alpha` (radians) and `offset_u`, and diagnostics
#'   (`M0`, `boundary_safe`, `avg_ordinates_per_bin`, `n_obs`, `J_n`, `omega`,
#'   and optionally `candidates`).
#'
#' @examples
#' # Offset-free default, quarterly (N = 4), fundamental P = 1, n = 60:
#' res <- suggest_M(P = 1, N = 4, n_obs = 60)
#' res$M      # 5
#' res$rho_M  # 0.2
#'
#' # The reference default offset grid can realize M = 4 with a half-bin
#' # offset, but that partition is not honored by the package's binning:
#' res2 <- suggest_M(P = 1, N = 4, n_obs = 60, offset_grid = c(0, 0.5))
#' res2$M         # 4
#' res2$offset_u  # 0.5
#'
#' @export
suggest_M <- function(P,
                      N,
                      n_obs = NULL,
                      target_rho = 0.25,
                      rho_bounds = c(0.15, 0.35),
                      min_ordinates_per_bin = NULL,
                      exclude_nyquist = TRUE,
                      search_min = NULL,
                      search_max = NULL,
                      offset_grid = 0,
                      boundary_tol = .Machine$double.eps^0.5,
                      return_candidates = FALSE) {

  if (length(target_rho) != 1L || !is.finite(target_rho) ||
      target_rho <= 0 || target_rho >= 1) {
    stop("`target_rho` must be a single number in (0, 1).")
  }

  if (length(rho_bounds) != 2L || any(!is.finite(rho_bounds)) ||
      any(rho_bounds <= 0) || any(rho_bounds >= 1) ||
      rho_bounds[1] >= rho_bounds[2]) {
    stop("`rho_bounds` must be two increasing numbers in (0, 1).")
  }

  omega <- omega_seasonal(P, N, exclude_nyquist = exclude_nyquist)
  H <- length(omega)

  if (H < 1L) {
    stop("No seasonal frequencies returned by `omega_seasonal()`.")
  }

  if (length(offset_grid) < 1L || any(!is.finite(offset_grid)) ||
      any(offset_grid < 0) || any(offset_grid >= 1)) {
    stop("`offset_grid` must be a non-empty vector of values in [0, 1).")
  }

  # Positive interior Fourier ordinates in (0, pi), omitting zero and Nyquist.
  J_n <- NA_integer_
  if (!is.null(n_obs)) {
    if (length(n_obs) != 1L || !is.finite(n_obs) || n_obs <= 2) {
      stop("`n_obs` must be a single integer greater than 2.")
    }

    n_obs <- as.integer(n_obs)

    J_n <- if (n_obs %% 2L == 0L) {
      n_obs / 2L - 1L
    } else {
      (n_obs - 1L) / 2L
    }

    if (!is.null(min_ordinates_per_bin)) {
      if (length(min_ordinates_per_bin) != 1L ||
          !is.finite(min_ordinates_per_bin) ||
          min_ordinates_per_bin <= 0) {
        stop("`min_ordinates_per_bin` must be a positive number.")
      }
    }
  }

  # First-order target based on H / target_rho.
  M0 <- ceiling(H / target_rho)

  if (is.null(search_min)) {
    search_min <- max(H + 1L, floor(0.50 * M0))
  }

  if (is.null(search_max)) {
    search_max <- max(ceiling(2.50 * M0), M0 + 50L)
  }

  search_min <- as.integer(search_min)
  search_max <- as.integer(search_max)

  # Need M > H for any chance of one harmonic per bin.
  if (search_min < H + 1L) {
    search_min <- H + 1L
  }

  if (search_max < search_min) {
    stop("`search_max` must be at least `search_min`.")
  }

  M_grid <- seq.int(search_min, search_max)

  eval_one_M <- function(M) {
    # Search the offset grid for the first alpha that gives a boundary-safe
    # partition. The partition is B_m = ((m-1)pi/M + alpha, m pi/M + alpha];
    # alpha = u * pi/M for u in offset_grid. A boundary hit occurs when
    # (omega - alpha) * M / pi is (numerically) an integer.
    chosen_u <- offset_grid[1]
    boundary_hit <- TRUE
    z <- M * omega / pi - chosen_u

    for (u in offset_grid) {
      z_try <- M * omega / pi - u
      hit <- any(abs(z_try - round(z_try)) <= boundary_tol)
      if (!hit) {
        chosen_u <- u
        boundary_hit <- FALSE
        z <- z_try
        break
      }
    }

    alpha <- chosen_u * pi / M

    # Bin index for B_m = ((m-1)pi/M + alpha, m pi/M + alpha].
    bin_id <- ceiling(z - boundary_tol)
    bin_id <- pmax(1L, pmin(M, as.integer(bin_id)))

    K_M <- length(unique(bin_id))
    rho_M <- K_M / M

    avg_ordinates_per_bin <- if (!is.na(J_n)) J_n / M else NA_real_

    feasible_occupancy <- TRUE
    if (!is.null(min_ordinates_per_bin) && !is.na(J_n)) {
      feasible_occupancy <- avg_ordinates_per_bin >= min_ordinates_per_bin
    }

    data.frame(
      M = M,
      H = H,
      K_M = K_M,
      rho_M = rho_M,
      boundary_safe = !boundary_hit,
      alpha = alpha,
      offset_u = chosen_u,
      avg_ordinates_per_bin = avg_ordinates_per_bin,
      feasible_occupancy = feasible_occupancy
    )
  }

  candidates <- do.call(rbind, lapply(M_grid, eval_one_M))

  # Require K_M == H: every distinct seasonal frequency must occupy its own
  # bin. Cases with K_M < H (harmonic merging) are excluded from feasibility.
  candidates$valid_basic <-
    candidates$boundary_safe &
    candidates$K_M == H &
    candidates$K_M < candidates$M &
    candidates$feasible_occupancy

  candidates$within_rho_bounds <-
    candidates$rho_M >= rho_bounds[1] &
    candidates$rho_M <= rho_bounds[2]

  candidates$score <- abs(candidates$rho_M - target_rho)

  feasible <- candidates[candidates$valid_basic, , drop = FALSE]

  if (nrow(feasible) < 1L) {
    stop("No feasible M found (every candidate either merges harmonics, lands on a boundary, or fails occupancy). Try increasing `search_max`, expanding `offset_grid`, relaxing occupancy constraints, or changing `rho_bounds`.")
  }

  feasible_in_bounds <- feasible[feasible$within_rho_bounds, , drop = FALSE]

  if (nrow(feasible_in_bounds) > 0L) {
    feasible <- feasible_in_bounds
  } else {
    warning("No feasible M satisfied `rho_bounds`; choosing the closest feasible M to `target_rho`.")
  }

  # Tie-breaking:
  #   1. closest rho_M to target_rho
  #   2. closest M to M0
  #   3. smaller M
  feasible$distance_from_M0 <- abs(feasible$M - M0)

  feasible <- feasible[order(feasible$score,
                             feasible$distance_from_M0,
                             feasible$M), ]

  best <- feasible[1L, ]

  out <- list(
    M = best$M,
    H = H,
    K_M = best$K_M,
    rho_M = best$rho_M,
    target_rho = target_rho,
    rho_bounds = rho_bounds,
    M0 = M0,
    boundary_safe = best$boundary_safe,
    alpha = best$alpha,
    offset_u = best$offset_u,
    avg_ordinates_per_bin = best$avg_ordinates_per_bin,
    min_ordinates_per_bin = min_ordinates_per_bin,
    n_obs = n_obs,
    J_n = J_n,
    omega = omega
  )

  if (isTRUE(return_candidates)) {
    out$candidates <- candidates
  }

  out
}
